### ISSUE TITLE
Todo: Feature recovery password

### ISSUE THREAD

**Issue by CarlosAugustoPO** [CarlosAugustoPO/plataforma-de-treinos#1]
## In templates/Cadastrar/index
- [ ] Create a link in sign in page
## In pages/recovery-password/index
- [ ] Create recovery-password page
-## in templates/RecoveryPassword/index
- [ ] Create recovery-password template
- [ ] Create recovery-password form
